### ISSUE TITLE
Qt Creator setup for ESP-IDF

### ISSUE THREAD

**Issue by Sterpa** [ascii78/ascii78.github.io#1]
According to your article http://blog.zolder.org/blog/esp-idf/
could you please explain, how you setup Qt Creator to work with ESP-IDF v3.3 (or 4.x)?

Your words in article:

> With QtCreator 4.8 everything is working quite well now. Just open a project with the CMakeLists.txt provided, all examples should have them included now. You do not have to use a custom xtensa kit, just use whatever you have with your QT/compiler installation.

looks very strange, because after installation QT Creator have no cmake, gcc compilers and know nothing about xtensa core. You should install it manualy, install toolchain and configure in QT Creator. All ESP-IDF examples have only two/three basic strings:

> cmake_minimum_required(VERSION 3.5)
> include($ENV{IDF_PATH}/tools/cmake/project.cmake)
> project(base)

and i absolutely don't understand, how you just open the project and begin to work...

Could you please explain, how you setup Qt Creator? What settings you have in Kits/Compilers/Debuggers/CMake in Tools/Options ?

Thanks a lot in advance!

**Comment by ascii78** [comment]
Yes, you need 4.x I'm not sure if it has been backported to 3.x, you also need to install it as per the documentation, IDF_PATH needs to be set before QT Creator is started. Then just "file>open file or project", in the dropdown you should see "CMake Project File (CMakeLists.txt)", if you select one qtcreator/cmake should start indexing and present you with a projects outline on the left as seen in the screenshot. The 3 lines are correct, all the complex stuff is done in IDF_PATH. Also regarding kit, I have it set to the standard desktop kit, but this is overwritten by CMake (there is a warning that says: "Cmake configuration set by the kit was overwritten in the project). Debugging unfortunately doesn't work.

**Comment by Sterpa** [comment]
I think we have misunderstanding.
In the last I've got "CMake project was parsed successfully" message, but only after manual setup steps:
(all steps after installing ESP-IDFv3.3 with [esp-idf-tools-setup-2.1.exe](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/windows-setup.html) tool and installing QT Cleator)
1. [Add IDF_PATH and PATH](https://docs.espressif.com/projects/esp-idf/en/stable/get-started-cmake/add-idf_path-to-profile.html#) into Windows Environment Variables. By default esp-idf-tools-setup-2.1.exe do not add this variables into Windows Environment, because usually you use it locally(not global) in Eclipse project or in special IDF-command prompt called by special cmd script. 
2. Add ESP-IDF CMake.exe to Tools/Options/Kits/CMake
![image](https://user-images.githubusercontent.com/7299203/69099036-e00d4a80-0a6a-11ea-890f-b9f5fb71741f.png)
3. Add Xtensa GCC compilers for C/C++ to Tools/Options/Kits/Compilers
![image](https://user-images.githubusercontent.com/7299203/69099222-4db97680-0a6b-11ea-9203-9dd989780b25.png)
![image](https://user-images.githubusercontent.com/7299203/69099252-5f028300-0a6b-11ea-9b26-74a2d90af710.png)
4. Add Compillers and Cmake tool to Kit (i make new one because Default use Clang)
![image](https://user-images.githubusercontent.com/7299203/69099423-c15b8380-0a6b-11ea-9f86-6a4a49880d85.png)
Only after this steps i could open Hello-World project and got "CMake project was parsed successfully"
But i cannot build it. I've got a long error and do not know, what happens...
```
01:10:03: Running steps for project base...
01:10:03: Starting: "C:\Users\mikha\.espressif\tools\cmake\3.13.4\bin\cmake.exe" --build . --target all
[1/6 12.9/sec] Performing build step for 'bootloader'
ninja: no work to do.
[2/4 12.0/sec] Generating esp32.project.ld
FAILED: esp-idf/esp32/esp32.project.ld 
cmd.exe /C "cd /D C:\msys32\home\mikha\esp\base\build\esp-idf\esp32 && python C:/Users/mikha/code/esp-idf/tools/ldgen/ldgen.py --config C:/msys32/home/mikha/esp/base/sdkconfig --fragments C:/Users/mikha/code/esp-idf/components/soc/linker.lf	C:/Users/mikha/code/esp-idf/components/heap/linker.lf	C:/Users/mikha/code/esp-idf/components/xtensa-debug-module/linker.lf	C:/Users/mikha/code/esp-idf/components/app_trace/linker.lf	C:/Users/mikha/code/esp-idf/components/freertos/linker.lf	C:/Users/mikha/code/esp-idf/components/esp_ringbuf/linker.lf	C:/Users/mikha/code/esp-idf/components/spi_flash/linker.lf	C:/Users/mikha/code/esp-idf/components/lwip/linker.lf	C:/Users/mikha/code/esp-idf/components/espcoredump/linker.lf	C:/Users/mikha/code/esp-idf/components/esp32/linker.lf	C:/Users/mikha/code/esp-idf/components/esp32/ld/esp32_fragments.lf --input C:/Users/mikha/code/esp-idf/components/esp32/ld/esp32.project.ld.in --output C:/msys32/home/mikha/esp/base/build/esp-idf/esp32/esp32.project.ld --sections C:/msys32/home/mikha/esp/base/build/ldgen.section_infos --kconfig C:/Users/mikha/code/esp-idf/Kconfig --env "COMPONENT_KCONFIGS= C:/Users/mikha/code/esp-idf/components/app_trace/Kconfig C:/Users/mikha/code/esp-idf/components/aws_iot/Kconfig C:/Users/mikha/code/esp-idf/components/bt/Kconfig C:/Users/mikha/code/esp-idf/components/driver/Kconfig C:/Users/mikha/code/esp-idf/components/efuse/Kconfig C:/Users/mikha/code/esp-idf/components/esp32/Kconfig C:/Users/mikha/code/esp-idf/components/esp_adc_cal/Kconfig C:/Users/mikha/code/esp-idf/components/esp_event/Kconfig C:/Users/mikha/code/esp-idf/components/esp_http_client/Kconfig C:/Users/mikha/code/esp-idf/components/esp_http_server/Kconfig C:/Users/mikha/code/esp-idf/components/esp_https_ota/Kconfig C:/Users/mikha/code/esp-idf/components/espcoredump/Kconfig C:/Users/mikha/code/esp-idf/components/ethernet/Kconfig C:/Users/mikha/code/esp-idf/components/fatfs/Kconfig C:/Users/mikha/code/esp-idf/components/freemodbus/Kconfig C:/Users/mikha/code/esp-idf/components/freertos/Kconfig C:/Users/mikha/code/esp-idf/components/heap/Kconfig C:/Users/mikha/code/esp-idf/components/libsodium/Kconfig C:/Users/mikha/code/esp-idf/components/log/Kconfig C:/Users/mikha/code/esp-idf/components/lwip/Kconfig C:/Users/mikha/code/esp-idf/components/mbedtls/Kconfig C:/Users/mikha/code/esp-idf/components/mdns/Kconfig C:/Users/mikha/code/esp-idf/components/mqtt/Kconfig C:/Users/mikha/code/esp-idf/components/nvs_flash/Kconfig C:/Users/mikha/code/esp-idf/components/openssl/Kconfig C:/Users/mikha/code/esp-idf/components/pthread/Kconfig C:/Users/mikha/code/esp-idf/components/spi_flash/Kconfig C:/Users/mikha/code/esp-idf/components/spiffs/Kconfig C:/Users/mikha/code/esp-idf/components/tcpip_adapter/Kconfig C:/Users/mikha/code/esp-idf/components/unity/Kconfig C:/Users/mikha/code/esp-idf/components/vfs/Kconfig C:/Users/mikha/code/esp-idf/components/wear_levelling/Kconfig C:/Users/mikha/code/esp-idf/components/wifi_provisioning/Kconfig" --env "COMPONENT_KCONFIGS_PROJBUILD= C:/Users/mikha/code/esp-idf/components/app_update/Kconfig.projbuild C:/msys32/home/mikha/esp/base/components/arduino-esp32/Kconfig.projbuild C:/Users/mikha/code/esp-idf/components/bootloader/Kconfig.projbuild C:/Users/mikha/code/esp-idf/components/esptool_py/Kconfig.projbuild C:/Users/mikha/code/esp-idf/components/partition_table/Kconfig.projbuild" --env IDF_CMAKE=y --env IDF_PATH=C:/Users/mikha/code/esp-idf --env IDF_TARGET=esp32"
Traceback (most recent call last):
  File "C:/Users/mikha/code/esp-idf/tools/ldgen/ldgen.py", line 22, in <module>
    from fragments import FragmentFileModel
  File "C:\Users\mikha\code\esp-idf\tools\ldgen\fragments.py", line 20, in <module>
    from sdkconfig import SDKConfig
  File "C:\Users\mikha\code\esp-idf\tools\ldgen\sdkconfig.py", line 18, in <module>
    from pyparsing import Word, printables, Combine, Literal, hexnums, quotedString, Optional, nums, removeQuotes, oneOf, Group, infixNotation, opAssoc
ModuleNotFoundError: No module named 'pyparsing'
ninja: build stopped: subcommand failed.
01:10:03: The process "C:\Users\mikha\.espressif\tools\cmake\3.13.4\bin\cmake.exe" exited with code 1.
Error while building/deploying project base (kit: ESP32)
The kit ESP32 has configuration issues which might be the root cause for this problem.
When executing step "CMake Build"
01:10:03: Elapsed time: 00:00.
```
I think it is because Qt Creator run "cmake --build", but ESP-IDF have to run "idf.py build" for cmake project.
Am i right?

**Comment by ascii78** [comment]
Okay in windows it is completely different, on the linux side everything is already set with most of the tools on the system. With regards to your building error, you could either build in cmd terminal or just set "idf.py build" as build step maybe. Also the missing pyparsing module could be do to different a python executable ? you probably need the one espressif is providing.

**Comment by ascii78** [comment]
So, out of curiousity I have checked it on windows now, it does work with following steps:

1.  Use  esp-idf-tools-setup-2.1.exe but check which python interpreter is used, I had an old one that came with platformio. I installed a clean python 3.8 from python.org and selected that in the installer.

2. When asked, use 4.0, I had some problems with 3.3

3. Indeed the tools are  not added to the path by the installer, I added them to my user PATH

![image](https://user-images.githubusercontent.com/1138654/69172948-11375a80-0aff-11ea-8749-6870b0ae156c.png)

4. Open up ESP-IDF command prompt, check that there are no warnings, especially about the python dependencies.

![image](https://user-images.githubusercontent.com/1138654/69173631-70499f00-0b00-11ea-805e-bb36f836767a.png)


5. On the same prompt go to examples/get-started/blink and run idf.py build, this should build. Remove any old CMakeLists.txt.user files (QT Creator extra information)

![image](https://user-images.githubusercontent.com/1138654/69173659-835c6f00-0b00-11ea-9128-593d4ffafe9d.png)

6. Now with QT Creator, remove all kits except Desktop:

![image](https://user-images.githubusercontent.com/1138654/69173409-00d3af80-0b00-11ea-9e9d-fd8d1f9de00a.png)

Compilers are autodetected because they are in path.

![image](https://user-images.githubusercontent.com/1138654/69173426-0af5ae00-0b00-11ea-883e-93a3146398fe.png)

No need for debugger.

![image](https://user-images.githubusercontent.com/1138654/69173480-295ba980-0b00-11ea-9ad0-ee7d399018f9.png)

__Do__ set cmake:

![image](https://user-images.githubusercontent.com/1138654/69173529-40020080-0b00-11ea-9b33-5a40295293e0.png)

7. Open CMakeLists.txt for hello world, input should now look like this, and cmake should parse properly.

![image](https://user-images.githubusercontent.com/1138654/69173904-07165b80-0b01-11ea-951c-6bcb04abe0d6.png)

(notice the errors, this is good, tab completion should now also work, this only works if you include the desktop kit)

![image](https://user-images.githubusercontent.com/1138654/69174006-42b12580-0b01-11ea-8afc-1f181150bc22.png)

8. Run "clean all" & "build all"

![image](https://user-images.githubusercontent.com/1138654/69174313-d3880100-0b01-11ea-9fca-09e593bdb4c4.png)

Hope that helps.

**Comment by Sterpa** [comment]
Thx a lot for so detailed instruction.
I do all as you say, but got a error when open hello_world: (Some Python dependencies must be installed. Check above message for details.)

> Running "C:\Users\mikha\.espressif\tools\cmake\3.13.4\bin\cmake.exe -E server "--pipe=\\.\pipe\{32ad567d-3eff-4063-9716-7175ecaec0a4}" --experimental" in C:\Users\mikha\AppData\Local\Temp\QtCreator-tfpvSy\qtc-cmake-HBWxRRfV.
> Starting to parse CMake project, using: "-DCMAKE_BUILD_TYPE:STRING=Debug", "-DCMAKE_CXX_COMPILER:STRING=", "-DCMAKE_C_COMPILER:STRING=C:/Qt/qtcreator-4.10.2/bin/clang/bin/clang.exe", "-DCMAKE_PREFIX_PATH:STRING=", "-DQT_QMAKE_EXECUTABLE:STRING=".
> Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.24.0.windows.2") 
> IDF_TARGET not set, using default target: esp32
> The C compiler identification is GNU 8.2.0
> The CXX compiler identification is GNU 8.2.0
> The ASM compiler identification is GNU
> Found assembler: C:/Users/mikha/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
> Check for working C compiler: C:/Users/mikha/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
> Check for working C compiler: C:/Users/mikha/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe -- works
> Detecting C compiler ABI info
> Detecting C compiler ABI info - done
> Detecting C compile features
> Detecting C compile features - done
> Check for working CXX compiler: C:/Users/mikha/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe
> Check for working CXX compiler: C:/Users/mikha/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe -- works
> Detecting CXX compiler ABI info
> Detecting CXX compiler ABI info - done
> Detecting CXX compile features
> Detecting CXX compile features - done
> Project version: v4.1-dev-1086-g93a8603c5
> Building ESP-IDF components for target esp32
> Checking Python dependencies...
> CMake Error at C:/Users/mikha/code/esp-idf/tools/cmake/build.cmake:270 (message):
>   Some Python dependencies must be installed.  Check above message for
>   details.
> Call Stack (most recent call first):
>   C:/Users/mikha/code/esp-idf/tools/cmake/build.cmake:396 (__build_check_python)
>   C:/Users/mikha/code/esp-idf/tools/cmake/project.cmake:357 (idf_build_process)
>   CMakeLists.txt:6 (project)
> 
> 
> Configuring incomplete, errors occurred!
> See also "C:/Users/mikha/AppData/Local/Temp/QtCreator-tfpvSy/qtc-cmake-HBWxRRfV/CMakeFiles/CMakeOutput.log".
> CMake Project parsing failed.

![image](https://user-images.githubusercontent.com/7299203/69193688-5fb51b00-0b38-11ea-8f61-d95abdb80937.png)

**Comment by ascii78** [comment]
Can you show both in "ESP-IDF Command Prompt" and a normal cmd.exe:

```
echo %PATH%
where python
python.exe %IDF_PATH%\tools\check_python_dependencies.py
```

It's probably pointing to the wrong python, the venv python is the one that's needed in $USER\\.espressif\python_env\idf4.0_py3.8_env\Scripts, it has all the libraries. Optionally install the needed dependencies in your global python installation. This should be something like: 

`C:\\Program Files (x86)\\Python38\\python.exe -m pip install --user -r C:\\Users\\$USER\\Desktop\\esp-idf\\requirements.txt`

**Comment by Sterpa** [comment]
Thx a lot for idea!
YES, `python -m pip install --user -r %IDF_PATH%/requirements.txt` helps to open and build the project.
And requirements installs on 
`c:\users\mikha\appdata\local\programs\python\python37\lib\site-packages` and
`c:\users\mikha\appdata\roaming\python\python37\site-packages` and
`C:\Users\mikha\AppData\Roaming\Python\Python37\Scripts` (futurize.exe and pasteurize.exe)

i do not understand why esp-idf-tools-setup-2.1.exe install scripts to another directory...
i also add `C:\Users\mikha\OneDrive\esp\.espressif\python_env\idf4.0_py3.7_env\Scripts` to the PATH
and i do not understand why Qt could not find <stdio.h> ??

The last question, how to call "RUN" ?
How to change RUN call to `idf.py -p COM5 flash` ?

ESP-IDF Command Prompt:
```
Using Python in C:\Users\mikha\AppData\Local\Programs\Python\Python37\
Python 3.7.4
Using Git in C:\Program Files\Git\cmd\
git version 2.24.0.windows.2
Setting IDF_PATH: C:\Users\mikha\OneDrive\esp\esp-idf

Adding ESP-IDF tools to PATH...
    C:\Users\mikha\OneDrive\esp\.espressif\python_env\idf4.0_py3.7_env\Scripts

Checking if Python packages are up to date...
Python requirements from C:\Users\mikha\OneDrive\esp\esp-idf\requirements.txt are satisfied.

Done! You can now compile ESP-IDF projects.
Go to the project directory and run:

  idf.py build


C:\Users\mikha\OneDrive\esp\esp-idf>echo %PATH%
C:\Users\mikha\OneDrive\esp\.espressif\python_env\idf4.0_py3.7_env\Scripts;C:\Users\mikha\AppData\Local\Programs\Python\Python37\;C:\Program Files\Git\cmd\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\mikha\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\mikha\AppData\Local\Programs\Python\Python37\;C:\Users\mikha\AppData\Local\Microsoft\WindowsApps;C:\Users\mikha\OneDrive\esp\.espressif\tools\cmake\3.13.4\bin;C:\Users\mikha\OneDrive\esp\.espressif\tools\openocd-esp32\v0.10.0-esp32-20190313\openocd-esp32\bin;C:\Users\mikha\OneDrive\esp\.espressif\tools\mconf\v4.6.0.0-idf-20190628\;C:\Users\mikha\OneDrive\esp\.espressif\tools\ninja\1.9.0\;C:\Users\mikha\OneDrive\esp\.espressif\tools\idf-exe\1.0.1\;C:\Users\mikha\OneDrive\esp\.espressif\tools\ccache\3.7\;C:\Users\mikha\OneDrive\esp\.espressif\tools\xtensa-esp32-elf\esp-2019r2-8.2.0\xtensa-esp32-elf\bin;C:\Users\mikha\OneDrive\esp\.espressif\tools\esp32ulp-elf\2.28.51.20170517\esp32ulp-elf-binutils\bin;C:\Users\mikha\OneDrive\esp\esp-idf\tools;

C:\Users\mikha\OneDrive\esp\esp-idf>where python
C:\Users\mikha\OneDrive\esp\.espressif\python_env\idf4.0_py3.7_env\Scripts\python.exe
C:\Users\mikha\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\mikha\AppData\Local\Microsoft\WindowsApps\python.exe

C:\Users\mikha\OneDrive\esp\esp-idf>python.exe %IDF_PATH%\tools\check_python_dependencies.py
Python requirements from C:\Users\mikha\OneDrive\esp\esp-idf\requirements.txt are satisfied.

C:\Users\mikha\OneDrive\esp\esp-idf>
```

CMD:
```
Microsoft Windows [Version 10.0.18362.476]
(c) Корпорация Майкрософт (Microsoft Corporation), 2019. Все права защищены.

C:\Users\mikha>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\mikha\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\mikha\AppData\Local\Programs\Python\Python37\;C:\Users\mikha\AppData\Local\Microsoft\WindowsApps;C:\Users\mikha\OneDrive\esp\.espressif\tools\cmake\3.13.4\bin;C:\Users\mikha\OneDrive\esp\.espressif\tools\openocd-esp32\v0.10.0-esp32-20190313\openocd-esp32\bin;C:\Users\mikha\OneDrive\esp\.espressif\tools\mconf\v4.6.0.0-idf-20190628\;C:\Users\mikha\OneDrive\esp\.espressif\tools\ninja\1.9.0\;C:\Users\mikha\OneDrive\esp\.espressif\tools\idf-exe\1.0.1\;C:\Users\mikha\OneDrive\esp\.espressif\tools\ccache\3.7\;C:\Users\mikha\OneDrive\esp\.espressif\tools\xtensa-esp32-elf\esp-2019r2-8.2.0\xtensa-esp32-elf\bin;C:\Users\mikha\OneDrive\esp\.espressif\tools\esp32ulp-elf\2.28.51.20170517\esp32ulp-elf-binutils\bin;C:\Users\mikha\OneDrive\esp\esp-idf\tools;

C:\Users\mikha>where python
C:\Users\mikha\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\mikha\AppData\Local\Microsoft\WindowsApps\python.exe

C:\Users\mikha>python.exe %IDF_PATH%\tools\check_python_dependencies.py
The following Python requirements are not satisfied:
click>=5.0
pyserial>=3.0
future>=0.15.2
cryptography>=2.1.4
pyparsing>=2.0.3,<2.4.0
pyelftools>=0.22
Please refer to the Get Started section of the ESP-IDF Programming Guide for setting up the required packages.
Alternatively, you can run "C:\\Users\\mikha\\AppData\\Local\\Programs\\Python\\Python37\\python.exe -m pip install --user -r C:\\Users\\mikha\\OneDrive\\esp\\esp-idf\\requirements.txt" for resolving the issue.

C:\Users\mikha>
```

**Comment by Matthias199** [comment]
hes did you solve the not finding of the stdio or how to include it properly ?
